name: 'Install Qt'
description: 'Install Qt on your Github Actions workflows with just one simple action'
author: 'jurplel'
branding:
  icon: 'package'
  color: 'green'
inputs:
  dir:
    description: 'Directory to install Qt'
  version:
    description: 'Version of Qt to install'
    default: '5.12.6'
  host:
    description: 'Host platform'
  target:
    description: 'Target platform for build'
    default: 'desktop'
  arch:
    description: 'Architecture for Windows/Android'
  install-deps:
    description: 'Whether or not to install Qt dependencies on Linux'
    default: 'true'
  modules:
    description: 'Additional Qt modules to install'
  tools_ifw:
    description: 'Additional tools to install'
runs:
  using: 'node12'
  main: 'lib/main.js'
